### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by davidbarratt** [diablodale/pinentry-wsl-ps1#2]
I follow the standard instructions, but I can't get the dialog to popup... gpg just hangs waiting for the password.

Am I doing something wrong?

**Comment by diablodale** [comment]
Thanks for giving it a try. 🙂 To help, I'll need more info. 

As a potential quick fix, I recommend using GPG2 v2.1.11 or greater. This is available in WSL using `sudo apt install gnupg2`. All my dev and testing was with this version of GPG2.

I just now pushed an update to clarify more and add troubleshooting. I recommend you read the updated README and download the newest code. This commit includes toast notification (on by default) if passwords are pulled from Windows Credential Manager. How to enable/disable is in the updated docs.

If the updated docs don't assist in fixing it... 
With the default GPG2 setup, not using this repo's code/config...  
Can you use GPG agent successfully using GPG keys _with passwords_ ?
Try a test. `gpg2 --clearsign myfile.zip`. Your entire console window should clear and present you an isolated password entry field in a crudely drawn box. Type in your key's password and it should return to your normal console with no error. And you should see the newly signed `myfile.zip.asc` file.

If that standard GPG2 setup doesn't work like that, particularly the full screen password prompt with the crude box, I recommend you first focus on getting your default setup working before moving to this custom pinentry.

If all works with this default GPG2 agent setup, then I need more info, please.

* Versions for Win10 `winver.exe` and WSL `uname -a` asdasd
* Version of Linux `cat /etc/lsb-release` and the DISTRIB_RELEASE value
* Versions of GPG `gpg --version` and/or GPG2 `gpg2 --version`
* Version of GPG agent `gpg-agent --version`
* Version of powershell `powershell -command "echo $PSVersionTable"` and the PSVersion value
* The specific steps you followed to install this repo's code
* The specific steps you followed which led to your failure case
* The specific meaning of "gpg just hangs waiting". What is all the output, UI, dialog, etc. that you received from GPG, Windows, or this code while you did your repro steps?
* What is your method to start gpg-agent? I discovered that there are many ways for gpg-agent to start and the options passed to it are inconsistent across the methods. I write about this in the updated docs.
* Please enable the logs as I describe in the updated docs (troubleshooting ideas 6 and 7). Remove the past logs you might have created. Then re-create your problem. Review the logs as you might see the problem. If not, attach the logs here in this issue. They should not have any passwords in them, though, I **_recommend you review your logs before posting_**.

**Comment by diablodale** [comment]
no reply from original poster. closing issue.
